title: Ryan's Page
description: A simple Jekyll theme
url: http://ryanarmstrong.me
avatar: /assets/img/web_profile_img_small.jpg
favicon: /assets/img/favicon.ico
google_analytics: # google analytics id
disqus_shortname: # disqus_shortname for disqus comment system
root: /

# Content for about page.
# Each paragraph will be a <p> tag which is inserted to about
# page. text_align is used to align the text. Default is left.
# Other two values are center and right. If there are some links
# in your paragraph, use '?link?' to take the place of a link.
# And then write the real link under links. name is the link
# text. url is the link. when external is set as true, then
# a new whidow will be open when link is clicked.
#
about:
  - paragraph: This is my web home. 
    text_align: left

  - paragraph: As a doctoral researcher,  I started the UB Doctoral Researchers in Business,
              an association to bring PhD students in management and organization together.
              More on that project ?link?. Actual research is important, too---so my supervisor
              keeps reminding me. A description of my work on performance measurement systems
              is on ?link?.
    text_align: left
    links:
      - name: here
        url: https://businessdoctorands.github.io
        external: false
      - name: research gate
        url: https://www.researchgate.net/profile/Ryan_Armstrong4
        external: false

  - paragraph: I pay my way through the PhD mainly through my work with ?link?. For more on my
               professional side see my ?link? page.  
    text_align: left
    links:
      - name: HireMojo
        url: https://hiremojo.com
        external: false
      - name: Linkedin
        url: https://www.linkedin.com/in/blendout/
        external: false        

  - paragraph: On the side I'm into playing around with the ?link?, exploring the Catalonian 
               countryside on foot or on bike, sustainable gardening, worm farms, eco-construction,
               reading philosophy, and trying to walk on my hands. I enjoy communicating in a general sense and welcome frequent interaction with humans and other mammals. 
               Do feel free to contact me, especially if we are related.
    text_align: left
    links:
      - name: web
        url: https://github.com/ryan-kwan-do
        external: false
  
    
