# Site settings
title: Ryan Armstrong's Hang Out Page
description: "A blog about Ryan Armstrong and his cats..."
baseurl: "" # for test: remove string '/space-jekyll-templa' to ''
url: "https://ryan-kwan-do.github.io" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https:yourusername.githu.io'
# User settings
username: Ryan Kwan Do
user_title: Researcher
email: hello@ryanarmstrong.me
twitter_username: ryan_kwan_do
github_username:  ryan-kwan-do
gplus_username:  rarmstrong
disqus_username: ryan-kwan-do

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: my posts
    url: /posts
  - title: series
    url: /series
  - title: tags
    url: /tags
  - title: about me
    url: /about
# projects in header index
projects:
 # - name: asciilang
 #  url: https://github.com/victorvoid/asciilang
 # - name: vim-frontend
 #   url: https://github.com/victorvoid/vim-frontend
 # - name: generator-capybara
 #   url: https://github.com/victorvoid/generator-capybara 
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
